### ISSUE TITLE
Data Limiting 

### ISSUE THREAD

**Issue by ashwin-pillai** [TIBCOSoftware/spotfire-mod-textcard#2]
Hello! Love this mod. However it seems that the data limiting is not being applied by the text card visualization. When I apply a limit data statement the card appears the same as without one.

**Comment by arnaudspotfire** [comment]
Hello,
I am not able to reproduce this issue. Are you able to provide an example DXP?

**Comment by ashwin-pillai** [comment]
Hello, I was able to resolve - it was an aggregation across the card by, content, and annotation that was causing the data limiting to not function as expected.

**Comment by arnaudspotfire** [comment]
Thank you for confirming.
